"""Unit tests for the HoneypotEvent data model (models.py)."""

import json
from datetime import datetime

from models import HoneypotEvent


def _event(**overrides):
    base = dict(
        protocol="ssh",
        src_ip="10.0.0.5",
        src_port=54321,
        dst_port=2222,
        event_type="connection",
    )
    base.update(overrides)
    return HoneypotEvent(**base)


def test_autogenerated_fields():
    e = _event()
    # event_id is a 12-char hex slug.
    assert len(e.event_id) == 12
    int(e.event_id, 16)
    # timestamp is a parseable ISO-8601 value.
    datetime.fromisoformat(e.timestamp)


def test_to_dict_preserves_fields():
    e = _event(payload="whoami", credentials={"username": "root", "password": "x"})
    d = e.to_dict()
    assert d["protocol"] == "ssh"
    assert d["credentials"]["username"] == "root"
    assert d["event_id"] == e.event_id


def test_to_json_is_valid_json():
    parsed = json.loads(_event().to_json())
    assert parsed["src_ip"] == "10.0.0.5"
    assert parsed["dst_port"] == 2222


def test_event_ids_are_unique():
    ids = {_event().event_id for _ in range(100)}
    assert len(ids) == 100
